import { Metadata } from "next";

export const metadata: Metadata = {
    title: "True Love Design ! Contacto",
    description: "Generated by create next app",
  };

export default function Contacto(){
    return(
        <h1>Contacto</h1>
    )
}