import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "app/components/Shared/Footer";
import { Header } from "app/components/Shared/Header";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "True Love Design ! Cineclub Forever",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
       <Footer />
      </body>
    </html>
  );
}
